#include "constanttext.hpp"

#include <calculate-core/calculate-core.hpp>

#include <QCoreApplication>

QString constantTitle(const QString& name) {
    for (const calculate_core::ConstantDescription& c : calculate_core::constants())
        if (QString::fromStdString(c.name) == name) return QCoreApplication::translate("constants", c.title.c_str());
    return {};
}

// The titles live in the engine; this list is what lupdate sees, so it keeps them in the translation file.
const QStringList& constantTextsForTranslation() {
    static const QStringList texts{
        QT_TRANSLATE_NOOP("constants", "pi"),
        QT_TRANSLATE_NOOP("constants", "Euler's number"),
        QT_TRANSLATE_NOOP("constants", "tau, 2π"),
        QT_TRANSLATE_NOOP("constants", "square root of 2"),
        QT_TRANSLATE_NOOP("constants", "golden ratio"),
        QT_TRANSLATE_NOOP("constants", "Euler–Mascheroni constant"),
        QT_TRANSLATE_NOOP("constants", "Catalan's constant"),
        QT_TRANSLATE_NOOP("constants", "Apéry's constant, ζ(3)"),
        QT_TRANSLATE_NOOP("constants", "plastic ratio"),
        QT_TRANSLATE_NOOP("constants", "omega constant, W(1)"),
        QT_TRANSLATE_NOOP("constants", "one million (10^6)"),
        QT_TRANSLATE_NOOP("constants", "one milliard (10^9)"),
        QT_TRANSLATE_NOOP("constants", "one billion (10^12)"),
        QT_TRANSLATE_NOOP("constants", "one billiard (10^15)"),
        QT_TRANSLATE_NOOP("constants", "one trillion (10^18)"),
        QT_TRANSLATE_NOOP("constants", "one trilliard (10^21)"),
        QT_TRANSLATE_NOOP("constants", "one quadrillion (10^24)"),
        QT_TRANSLATE_NOOP("constants", "one quintillion (10^30)"),
        QT_TRANSLATE_NOOP("constants", "one sextillion (10^36)"),
        QT_TRANSLATE_NOOP("constants", "one septillion (10^42)"),
        QT_TRANSLATE_NOOP("constants", "one octillion (10^48)"),
        QT_TRANSLATE_NOOP("constants", "one nonillion (10^54)"),
        QT_TRANSLATE_NOOP("constants", "one decillion (10^60)"),
        QT_TRANSLATE_NOOP("constants", "one googol (10^100)"),
        QT_TRANSLATE_NOOP("constants", "one lakh (10^5)"),
        QT_TRANSLATE_NOOP("constants", "one crore (10^7)"),
        QT_TRANSLATE_NOOP("constants", "one dozen (12)"),
        QT_TRANSLATE_NOOP("constants", "one gross (144)"),
        QT_TRANSLATE_NOOP("constants", "one score (20)"),
        QT_TRANSLATE_NOOP("constants", "parts per million"),
        QT_TRANSLATE_NOOP("constants", "per cent mille (10^-5)"),
        QT_TRANSLATE_NOOP("constants", "one million (10^6) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one milliard (10^9) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one billion (10^12) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one trillion (10^18) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one quadrillion (10^24) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one quintillion (10^30) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one sextillion (10^36) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one septillion (10^42) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one octillion (10^48) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one nonillion (10^54) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one decillion (10^60) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one dozen (12) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "one gross (144) (Spanish name)"),
        QT_TRANSLATE_NOOP("constants", "speed of light in vacuum"),
        QT_TRANSLATE_NOOP("constants", "Planck constant"),
        QT_TRANSLATE_NOOP("constants", "reduced Planck constant"),
        QT_TRANSLATE_NOOP("constants", "elementary charge"),
        QT_TRANSLATE_NOOP("constants", "Boltzmann constant"),
        QT_TRANSLATE_NOOP("constants", "Avogadro constant"),
        QT_TRANSLATE_NOOP("constants", "hyperfine transition frequency of Cs-133"),
        QT_TRANSLATE_NOOP("constants", "luminous efficacy"),
        QT_TRANSLATE_NOOP("constants", "Newtonian constant of gravitation"),
        QT_TRANSLATE_NOOP("constants", "standard acceleration of gravity"),
        QT_TRANSLATE_NOOP("constants", "standard atmosphere"),
        QT_TRANSLATE_NOOP("constants", "standard-state pressure"),
        QT_TRANSLATE_NOOP("constants", "molar gas constant"),
        QT_TRANSLATE_NOOP("constants", "Faraday constant"),
        QT_TRANSLATE_NOOP("constants", "Stefan-Boltzmann constant"),
        QT_TRANSLATE_NOOP("constants", "first radiation constant"),
        QT_TRANSLATE_NOOP("constants", "first radiation constant for spectral radiance"),
        QT_TRANSLATE_NOOP("constants", "second radiation constant"),
        QT_TRANSLATE_NOOP("constants", "molar volume of ideal gas (273.15 K, 100 kPa)"),
        QT_TRANSLATE_NOOP("constants", "molar volume of ideal gas (273.15 K, 101.325 kPa)"),
        QT_TRANSLATE_NOOP("constants", "Loschmidt constant (273.15 K, 100 kPa)"),
        QT_TRANSLATE_NOOP("constants", "Loschmidt constant (273.15 K, 101.325 kPa)"),
        QT_TRANSLATE_NOOP("constants", "molar mass constant"),
        QT_TRANSLATE_NOOP("constants", "vacuum mag. permeability"),
        QT_TRANSLATE_NOOP("constants", "vacuum electric permittivity"),
        QT_TRANSLATE_NOOP("constants", "characteristic impedance of vacuum"),
        QT_TRANSLATE_NOOP("constants", "fine-structure constant"),
        QT_TRANSLATE_NOOP("constants", "inverse fine-structure constant"),
        QT_TRANSLATE_NOOP("constants", "Rydberg constant"),
        QT_TRANSLATE_NOOP("constants", "Bohr radius"),
        QT_TRANSLATE_NOOP("constants", "Hartree energy"),
        QT_TRANSLATE_NOOP("constants", "classical electron radius"),
        QT_TRANSLATE_NOOP("constants", "Thomson cross section"),
        QT_TRANSLATE_NOOP("constants", "Compton wavelength"),
        QT_TRANSLATE_NOOP("constants", "reduced Compton wavelength"),
        QT_TRANSLATE_NOOP("constants", "Bohr magneton"),
        QT_TRANSLATE_NOOP("constants", "nuclear magneton"),
        QT_TRANSLATE_NOOP("constants", "mag. flux quantum"),
        QT_TRANSLATE_NOOP("constants", "conductance quantum"),
        QT_TRANSLATE_NOOP("constants", "Josephson constant"),
        QT_TRANSLATE_NOOP("constants", "von Klitzing constant"),
        QT_TRANSLATE_NOOP("constants", "electron volt"),
        QT_TRANSLATE_NOOP("constants", "atomic mass constant"),
        QT_TRANSLATE_NOOP("constants", "electron mass"),
        QT_TRANSLATE_NOOP("constants", "proton mass"),
        QT_TRANSLATE_NOOP("constants", "neutron mass"),
        QT_TRANSLATE_NOOP("constants", "deuteron mass"),
        QT_TRANSLATE_NOOP("constants", "helion mass"),
        QT_TRANSLATE_NOOP("constants", "triton mass"),
        QT_TRANSLATE_NOOP("constants", "alpha particle mass"),
        QT_TRANSLATE_NOOP("constants", "muon mass"),
        QT_TRANSLATE_NOOP("constants", "tau mass"),
        QT_TRANSLATE_NOOP("constants", "electron mass in u"),
        QT_TRANSLATE_NOOP("constants", "proton mass in u"),
        QT_TRANSLATE_NOOP("constants", "neutron mass in u"),
        QT_TRANSLATE_NOOP("constants", "electron mass energy equivalent in MeV"),
        QT_TRANSLATE_NOOP("constants", "proton mass energy equivalent in MeV"),
        QT_TRANSLATE_NOOP("constants", "neutron mass energy equivalent in MeV"),
        QT_TRANSLATE_NOOP("constants", "muon mass energy equivalent in MeV"),
        QT_TRANSLATE_NOOP("constants", "proton-electron mass ratio"),
        QT_TRANSLATE_NOOP("constants", "muon-electron mass ratio"),
        QT_TRANSLATE_NOOP("constants", "electron mag. mom."),
        QT_TRANSLATE_NOOP("constants", "proton mag. mom."),
        QT_TRANSLATE_NOOP("constants", "neutron mag. mom."),
        QT_TRANSLATE_NOOP("constants", "muon mag. mom."),
        QT_TRANSLATE_NOOP("constants", "electron g factor"),
        QT_TRANSLATE_NOOP("constants", "proton g factor"),
        QT_TRANSLATE_NOOP("constants", "muon g factor"),
        QT_TRANSLATE_NOOP("constants", "electron mag. mom. anomaly"),
        QT_TRANSLATE_NOOP("constants", "muon mag. mom. anomaly"),
        QT_TRANSLATE_NOOP("constants", "electron gyromag. ratio"),
        QT_TRANSLATE_NOOP("constants", "proton gyromag. ratio"),
        QT_TRANSLATE_NOOP("constants", "proton rms charge radius"),
        QT_TRANSLATE_NOOP("constants", "deuteron rms charge radius"),
        QT_TRANSLATE_NOOP("constants", "electron charge to mass quotient"),
        QT_TRANSLATE_NOOP("constants", "Boltzmann constant in eV/K"),
        QT_TRANSLATE_NOOP("constants", "Planck constant in eV/Hz"),
        QT_TRANSLATE_NOOP("constants", "reduced Planck constant in eV s"),
        QT_TRANSLATE_NOOP("constants", "reduced Planck constant times c in MeV fm"),
        QT_TRANSLATE_NOOP("constants", "Rydberg constant times hc in eV"),
        QT_TRANSLATE_NOOP("constants", "Hartree energy in eV"),
        QT_TRANSLATE_NOOP("constants", "molar Planck constant"),
        QT_TRANSLATE_NOOP("constants", "Fermi coupling constant"),
        QT_TRANSLATE_NOOP("constants", "weak mixing angle"),
        QT_TRANSLATE_NOOP("constants", "W to Z mass ratio"),
        QT_TRANSLATE_NOOP("constants", "Planck length"),
        QT_TRANSLATE_NOOP("constants", "Planck mass"),
        QT_TRANSLATE_NOOP("constants", "Planck time"),
        QT_TRANSLATE_NOOP("constants", "Planck temperature"),
    };
    return texts;
}
