#include "functiontext.hpp"

#include <QCoreApplication>

QString functionTitle(const calculate_core::FunctionDescription& f) {
    return QCoreApplication::translate("functions", f.title.c_str());
}

QString functionDescription(const calculate_core::FunctionDescription& f) {
    return QCoreApplication::translate("functions", f.description.c_str());
}

// The texts live in the engine; this list is what lupdate sees, so it keeps them in the translation file.
const QStringList& functionTextsForTranslation() {
    static const QStringList texts{
        QT_TRANSLATE_NOOP("functions", "Pi"),
        QT_TRANSLATE_NOOP("functions", "The ratio of a circle's circumference to its diameter."),
        QT_TRANSLATE_NOOP("functions", "Euler's number"),
        QT_TRANSLATE_NOOP("functions", "The base of the natural logarithm."),
        QT_TRANSLATE_NOOP("functions", "Square root"),
        QT_TRANSLATE_NOOP("functions", "The non-negative number whose square is x."),
        QT_TRANSLATE_NOOP("functions", "Cube root"),
        QT_TRANSLATE_NOOP("functions", "The real number whose cube is x."),
        QT_TRANSLATE_NOOP("functions", "n-th root"),
        QT_TRANSLATE_NOOP("functions", "The real number whose n-th power is x."),
        QT_TRANSLATE_NOOP("functions", "Exponential"),
        QT_TRANSLATE_NOOP("functions", "e raised to the power x."),
        QT_TRANSLATE_NOOP("functions", "Power of two"),
        QT_TRANSLATE_NOOP("functions", "2 raised to the power x."),
        QT_TRANSLATE_NOOP("functions", "Power of ten"),
        QT_TRANSLATE_NOOP("functions", "10 raised to the power x."),
        QT_TRANSLATE_NOOP("functions", "Square"),
        QT_TRANSLATE_NOOP("functions", "x times x."),
        QT_TRANSLATE_NOOP("functions", "Square root of x·π"),
        QT_TRANSLATE_NOOP("functions", "The square root of x times pi."),
        QT_TRANSLATE_NOOP("functions", "Hypotenuse"),
        QT_TRANSLATE_NOOP("functions", "The square root of x² + y², without overflow."),
        QT_TRANSLATE_NOOP("functions", "Natural logarithm"),
        QT_TRANSLATE_NOOP("functions", "The power to which e must be raised to give x."),
        QT_TRANSLATE_NOOP("functions", "Logarithm"),
        QT_TRANSLATE_NOOP("functions", "The logarithm of x in base 10 (or e, when the setting says so), or in the given base."),
        QT_TRANSLATE_NOOP("functions", "Binary logarithm"),
        QT_TRANSLATE_NOOP("functions", "The power to which 2 must be raised to give x."),
        QT_TRANSLATE_NOOP("functions", "Sine"),
        QT_TRANSLATE_NOOP("functions", "The sine of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Cosine"),
        QT_TRANSLATE_NOOP("functions", "The cosine of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Tangent"),
        QT_TRANSLATE_NOOP("functions", "The tangent of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Secant"),
        QT_TRANSLATE_NOOP("functions", "One over the cosine of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Cosecant"),
        QT_TRANSLATE_NOOP("functions", "One over the sine of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Cotangent"),
        QT_TRANSLATE_NOOP("functions", "The cosine over the sine of the angle x."),
        QT_TRANSLATE_NOOP("functions", "Inverse sine"),
        QT_TRANSLATE_NOOP("functions", "The angle in [−90°, 90°] whose sine is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse cosine"),
        QT_TRANSLATE_NOOP("functions", "The angle in [0°, 180°] whose cosine is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse tangent"),
        QT_TRANSLATE_NOOP("functions", "The angle in (−90°, 90°) whose tangent is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse secant"),
        QT_TRANSLATE_NOOP("functions", "The angle whose secant is x, the inverse cosine of 1/x."),
        QT_TRANSLATE_NOOP("functions", "Inverse cosecant"),
        QT_TRANSLATE_NOOP("functions", "The angle whose cosecant is x, the inverse sine of 1/x."),
        QT_TRANSLATE_NOOP("functions", "Inverse cotangent"),
        QT_TRANSLATE_NOOP("functions", "The angle whose cotangent is x: the inverse tangent of 1/x, and 90° at 0."),
        QT_TRANSLATE_NOOP("functions", "Angle of a point"),
        QT_TRANSLATE_NOOP("functions", "The angle in (−180°, 180°] of the point (x, y)."),
        QT_TRANSLATE_NOOP("functions", "Cardinal sine"),
        QT_TRANSLATE_NOOP("functions", "sin(x)/x, and 1 at 0."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic sine"),
        QT_TRANSLATE_NOOP("functions", "(eˣ − e⁻ˣ)/2."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic cosine"),
        QT_TRANSLATE_NOOP("functions", "(eˣ + e⁻ˣ)/2."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic tangent"),
        QT_TRANSLATE_NOOP("functions", "sinh(x)/cosh(x)."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic secant"),
        QT_TRANSLATE_NOOP("functions", "One over cosh(x)."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic cosecant"),
        QT_TRANSLATE_NOOP("functions", "One over sinh(x)."),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic cotangent"),
        QT_TRANSLATE_NOOP("functions", "cosh(x)/sinh(x)."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic sine"),
        QT_TRANSLATE_NOOP("functions", "The number whose hyperbolic sine is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic cosine"),
        QT_TRANSLATE_NOOP("functions", "The non-negative number whose hyperbolic cosine is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic tangent"),
        QT_TRANSLATE_NOOP("functions", "The number whose hyperbolic tangent is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic secant"),
        QT_TRANSLATE_NOOP("functions", "The non-negative number whose hyperbolic secant is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic cosecant"),
        QT_TRANSLATE_NOOP("functions", "The number whose hyperbolic cosecant is x."),
        QT_TRANSLATE_NOOP("functions", "Inverse hyperbolic cotangent"),
        QT_TRANSLATE_NOOP("functions", "The number whose hyperbolic cotangent is x."),
        QT_TRANSLATE_NOOP("functions", "Absolute value"),
        QT_TRANSLATE_NOOP("functions", "x without its sign."),
        QT_TRANSLATE_NOOP("functions", "Sign"),
        QT_TRANSLATE_NOOP("functions", "−1, 0 or 1, as x is negative, zero or positive."),
        QT_TRANSLATE_NOOP("functions", "Round down"),
        QT_TRANSLATE_NOOP("functions", "The largest whole number not above x."),
        QT_TRANSLATE_NOOP("functions", "Round up"),
        QT_TRANSLATE_NOOP("functions", "The smallest whole number not below x."),
        QT_TRANSLATE_NOOP("functions", "Round"),
        QT_TRANSLATE_NOOP("functions", "The nearest whole number; halves away from zero."),
        QT_TRANSLATE_NOOP("functions", "Integer part"),
        QT_TRANSLATE_NOOP("functions", "x without its fractional part, rounded toward zero."),
        QT_TRANSLATE_NOOP("functions", "Fractional part"),
        QT_TRANSLATE_NOOP("functions", "x minus its integer part."),
        QT_TRANSLATE_NOOP("functions", "Clip"),
        QT_TRANSLATE_NOOP("functions", "x, limited to the range from lo to hi."),
        QT_TRANSLATE_NOOP("functions", "Numerator"),
        QT_TRANSLATE_NOOP("functions", "The numerator of x as a reduced fraction."),
        QT_TRANSLATE_NOOP("functions", "Denominator"),
        QT_TRANSLATE_NOOP("functions", "The denominator of x as a reduced fraction."),
        QT_TRANSLATE_NOOP("functions", "Modulo"),
        QT_TRANSLATE_NOOP("functions", "The remainder of a divided by b, with the sign of a (or of b, when the setting says so)."),
        QT_TRANSLATE_NOOP("functions", "Remainder"),
        QT_TRANSLATE_NOOP("functions", "The remainder of a divided by b, with the sign of a."),
        QT_TRANSLATE_NOOP("functions", "Floored remainder"),
        QT_TRANSLATE_NOOP("functions", "The remainder of a divided by b, with the sign of b."),
        QT_TRANSLATE_NOOP("functions", "Greatest common divisor"),
        QT_TRANSLATE_NOOP("functions", "The largest whole number dividing both a and b."),
        QT_TRANSLATE_NOOP("functions", "Least common multiple"),
        QT_TRANSLATE_NOOP("functions", "The smallest positive whole number divisible by a and b."),
        QT_TRANSLATE_NOOP("functions", "Combinations"),
        QT_TRANSLATE_NOOP("functions", "The ways to choose r of n things, order ignored."),
        QT_TRANSLATE_NOOP("functions", "Permutations"),
        QT_TRANSLATE_NOOP("functions", "The ways to arrange r of n things in order."),
        QT_TRANSLATE_NOOP("functions", "Mean"),
        QT_TRANSLATE_NOOP("functions", "The sum of the values over their count."),
        QT_TRANSLATE_NOOP("functions", "Median"),
        QT_TRANSLATE_NOOP("functions", "The middle value, or the mean of the two middle ones."),
        QT_TRANSLATE_NOOP("functions", "Sample variance"),
        QT_TRANSLATE_NOOP("functions", "The squared deviations from the mean over n − 1."),
        QT_TRANSLATE_NOOP("functions", "Sample standard deviation"),
        QT_TRANSLATE_NOOP("functions", "The square root of the sample variance."),
        QT_TRANSLATE_NOOP("functions", "Population variance"),
        QT_TRANSLATE_NOOP("functions", "The squared deviations from the mean over n."),
        QT_TRANSLATE_NOOP("functions", "Population standard deviation"),
        QT_TRANSLATE_NOOP("functions", "The square root of the population variance."),
        QT_TRANSLATE_NOOP("functions", "Sum"),
        QT_TRANSLATE_NOOP("functions", "The term added up for each whole value of its variable from `from` to `to`."),
        QT_TRANSLATE_NOOP("functions", "Product"),
        QT_TRANSLATE_NOOP("functions", "The term multiplied for each whole value of its variable from `from` to `to`."),
        QT_TRANSLATE_NOOP("functions", "Gamma function"),
        QT_TRANSLATE_NOOP("functions", "The factorial extended to real numbers: gamma(n) = (n − 1)!."),
        QT_TRANSLATE_NOOP("functions", "Log-gamma"),
        QT_TRANSLATE_NOOP("functions", "The natural logarithm of the absolute value of gamma(x)."),
        QT_TRANSLATE_NOOP("functions", "Digamma"),
        QT_TRANSLATE_NOOP("functions", "The derivative of lgamma."),
        QT_TRANSLATE_NOOP("functions", "Beta function"),
        QT_TRANSLATE_NOOP("functions", "gamma(a)·gamma(b)/gamma(a + b)."),
        QT_TRANSLATE_NOOP("functions", "Error function"),
        QT_TRANSLATE_NOOP("functions", "2/√π times the integral of e^(−t²) from 0 to x."),
        QT_TRANSLATE_NOOP("functions", "Complementary error function"),
        QT_TRANSLATE_NOOP("functions", "1 − erf(x), accurate even when tiny."),
        QT_TRANSLATE_NOOP("functions", "Inverse error function"),
        QT_TRANSLATE_NOOP("functions", "The x with erf(x) = y."),
        QT_TRANSLATE_NOOP("functions", "Inverse complementary error function"),
        QT_TRANSLATE_NOOP("functions", "The x with erfc(x) = z."),
        QT_TRANSLATE_NOOP("functions", "Regularized lower incomplete gamma"),
        QT_TRANSLATE_NOOP("functions", "The integral of t^(a−1) e^(−t) from 0 to x, over gamma(a)."),
        QT_TRANSLATE_NOOP("functions", "Regularized upper incomplete gamma"),
        QT_TRANSLATE_NOOP("functions", "1 − gammap(a, x), accurate even when tiny."),
        QT_TRANSLATE_NOOP("functions", "Upper incomplete gamma"),
        QT_TRANSLATE_NOOP("functions", "The integral of t^(a−1) e^(−t) from x to infinity."),
        QT_TRANSLATE_NOOP("functions", "Lower incomplete gamma"),
        QT_TRANSLATE_NOOP("functions", "The integral of t^(a−1) e^(−t) from 0 to x."),
        QT_TRANSLATE_NOOP("functions", "Regularized incomplete beta"),
        QT_TRANSLATE_NOOP("functions", "The integral of t^(a−1)(1 − t)^(b−1) from 0 to x, over beta(a, b)."),
        QT_TRANSLATE_NOOP("functions", "Inverse incomplete beta"),
        QT_TRANSLATE_NOOP("functions", "The x with betainc(a, b, x) = y."),
        QT_TRANSLATE_NOOP("functions", "Constants"),
        QT_TRANSLATE_NOOP("functions", "Powers and roots"),
        QT_TRANSLATE_NOOP("functions", "Logarithms"),
        QT_TRANSLATE_NOOP("functions", "Trigonometry"),
        QT_TRANSLATE_NOOP("functions", "Hyperbolic"),
        QT_TRANSLATE_NOOP("functions", "Rounding and parts"),
        QT_TRANSLATE_NOOP("functions", "Integers"),
        QT_TRANSLATE_NOOP("functions", "Statistics"),
        QT_TRANSLATE_NOOP("functions", "Sums and products"),
        QT_TRANSLATE_NOOP("functions", "Special functions"),
        QT_TRANSLATE_NOOP("functions", "Probability"),
        QT_TRANSLATE_NOOP("functions", "Tau"),
        QT_TRANSLATE_NOOP("functions", "Twice pi: the ratio of a circle's circumference to its radius."),
        QT_TRANSLATE_NOOP("functions", "Square root of 2"),
        QT_TRANSLATE_NOOP("functions", "The positive number whose square is 2."),
        QT_TRANSLATE_NOOP("functions", "Golden ratio"),
        QT_TRANSLATE_NOOP("functions", "(1 + √5)/2, the positive root of x² = x + 1."),
        QT_TRANSLATE_NOOP("functions", "Euler–Mascheroni constant"),
        QT_TRANSLATE_NOOP("functions", "The limit of 1 + 1/2 + … + 1/n − ln n."),
        QT_TRANSLATE_NOOP("functions", "Catalan's constant"),
        QT_TRANSLATE_NOOP("functions", "1 − 1/3² + 1/5² − 1/7² + …, over the odd squares with alternating signs."),
        QT_TRANSLATE_NOOP("functions", "Apéry's constant"),
        QT_TRANSLATE_NOOP("functions", "1 + 1/2³ + 1/3³ + …, the value of zeta(3)."),
        QT_TRANSLATE_NOOP("functions", "Plastic ratio"),
        QT_TRANSLATE_NOOP("functions", "The real root of x³ = x + 1."),
        QT_TRANSLATE_NOOP("functions", "Omega constant"),
        QT_TRANSLATE_NOOP("functions", "The number x with x·eˣ = 1."),
        QT_TRANSLATE_NOOP("functions", "Value with uncertainty"),
        QT_TRANSLATE_NOOP("functions", "x, whose true value lies within u of it."),
        QT_TRANSLATE_NOOP("functions", "Error part"),
        QT_TRANSLATE_NOOP("functions", "The worst-case uncertainty x carries from its uncertain inputs, as a number."),
        QT_TRANSLATE_NOOP("functions", "Uncertainty"),
        QT_TRANSLATE_NOOP("functions", "Stored bits"),
        QT_TRANSLATE_NOOP("functions", "The sign, exponent and fraction fields of x as stored in a format."),
        QT_TRANSLATE_NOOP("functions", "Stored parts"),
        QT_TRANSLATE_NOOP("functions", "x as stored: sign, power of two and significand."),
        QT_TRANSLATE_NOOP("functions", "Stored value"),
        QT_TRANSLATE_NOOP("functions", "The value a format actually stores for x, exactly."),
        QT_TRANSLATE_NOOP("functions", "Conversion error"),
        QT_TRANSLATE_NOOP("functions", "Stored value minus x, exactly."),
        QT_TRANSLATE_NOOP("functions", "Signed"),
        QT_TRANSLATE_NOOP("functions", "x wrapped into that many bits, read as two's complement (the top bit counts as negative)."),
        QT_TRANSLATE_NOOP("functions", "Unsigned"),
        QT_TRANSLATE_NOOP("functions", "x wrapped into that many bits, read without a sign."),
        QT_TRANSLATE_NOOP("functions", "Number from bits"),
        QT_TRANSLATE_NOOP("functions", "The number a bit pattern stands for in a format."),
        QT_TRANSLATE_NOOP("functions", "Floating point")
    };
    return texts;
}
